/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class Baixa extends javax.swing.JPanel {

    JPanel paineis;

    /**
     * Creates new form Baixa
     */
    public Baixa(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JLabel();
        produtos = new javax.swing.JComboBox<>();
        separadorMovimentacao = new javax.swing.JSeparator();
        nome = new javax.swing.JTextField();
        confirmar = new javax.swing.JPanel();
        labelConfirmar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emEstoque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorMovimentacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        estoqueAtual = new javax.swing.JTextField();
        separadorProduto = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setText("Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        produtos.setBackground(new java.awt.Color(242, 242, 242));
        produtos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aaaa", "aab", "baa", "caa", "abb" }));
        produtos.setBorder(null);
        add(produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 70, 560, 30));

        separadorMovimentacao.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorMovimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 10));

        nome.setBackground(new java.awt.Color(242, 242, 242));
        nome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(51, 51, 51));
        nome.setBorder(null);
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeKeyTyped(evt);
            }
        });
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 600, 70));

        confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmarMouseExited(evt);
            }
        });
        confirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar.setText("Confirmar");
        labelConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelConfirmarMousePressed(evt);
            }
        });
        confirmar.add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 80, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Produto:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 70, -1));

        codigoProduto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        codigoProduto.setForeground(new java.awt.Color(51, 51, 51));
        codigoProduto.setBorder(null);
        codigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoProdutoFocusLost(evt);
            }
        });
        codigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoActionPerformed(evt);
            }
        });
        codigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoProdutoKeyTyped(evt);
            }
        });
        add(codigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Estoque:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 70, -1));

        emEstoque.setBackground(new java.awt.Color(242, 242, 242));
        emEstoque.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        emEstoque.setForeground(new java.awt.Color(51, 51, 51));
        emEstoque.setBorder(null);
        emEstoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emEstoqueFocusLost(evt);
            }
        });
        emEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emEstoqueActionPerformed(evt);
            }
        });
        emEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emEstoqueKeyTyped(evt);
            }
        });
        add(emEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 130, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Movimentação:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, -1));

        valorMovimentacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        valorMovimentacao.setForeground(new java.awt.Color(51, 51, 51));
        valorMovimentacao.setBorder(null);
        valorMovimentacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorMovimentacaoFocusLost(evt);
            }
        });
        valorMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorMovimentacaoActionPerformed(evt);
            }
        });
        valorMovimentacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorMovimentacaoKeyTyped(evt);
            }
        });
        add(valorMovimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Estoque atual:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, -1));

        estoqueAtual.setBackground(new java.awt.Color(242, 242, 242));
        estoqueAtual.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        estoqueAtual.setForeground(new java.awt.Color(51, 51, 51));
        estoqueAtual.setBorder(null);
        estoqueAtual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                estoqueAtualFocusLost(evt);
            }
        });
        estoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueAtualActionPerformed(evt);
            }
        });
        estoqueAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estoqueAtualKeyTyped(evt);
            }
        });
        add(estoqueAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 130, 30));

        separadorProduto.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 10));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Produto não encontrado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "movimentacoes");
    }//GEN-LAST:event_voltarMouseClicked

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        //        String conteudo = jTextField1.getText();
        //        String conteudoAvaliado = conteudo.replaceAll("[^ A-z]", "");
        //        System.out.println(conteudoAvaliado);
        //        //POSSO USAR O MATCH AQUI
        //        if (conteudo.equals(conteudoAvaliado) == false){
            //            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
            //            nomeInvalido.setForeground(Color.red);
            //            imagemCampoInválido.setVisible(true);
            //        } else {
            //            nomeInvalido.setText("");
            //            imagemCampoInválido.setVisible(false);
            //        }
    }//GEN-LAST:event_nomeFocusLost

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyTyped

    }//GEN-LAST:event_nomeKeyTyped

    private void labelConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseClicked
        JOptionPane.showMessageDialog(this, "clicou");
    }//GEN-LAST:event_labelConfirmarMouseClicked

    private void labelConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseEntered
        confirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_labelConfirmarMouseEntered

    private void labelConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseExited
        confirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMouseExited

    private void labelConfirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMousePressed
        confirmar.setBackground(Color.white);
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMousePressed

    private void confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseClicked

    }//GEN-LAST:event_confirmarMouseClicked

    private void confirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseEntered
        confirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_confirmarMouseEntered

    private void confirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseExited
        confirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_confirmarMouseExited

    private void codigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoProdutoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoFocusLost

    private void codigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoActionPerformed

    private void codigoProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoProdutoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoKeyTyped

    private void emEstoqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emEstoqueFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emEstoqueFocusLost

    private void emEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emEstoqueActionPerformed

    private void emEstoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emEstoqueKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emEstoqueKeyTyped

    private void valorMovimentacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorMovimentacaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMovimentacaoFocusLost

    private void valorMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorMovimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMovimentacaoActionPerformed

    private void valorMovimentacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorMovimentacaoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMovimentacaoKeyTyped

    private void estoqueAtualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estoqueAtualFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueAtualFocusLost

    private void estoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueAtualActionPerformed

    private void estoqueAtualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estoqueAtualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueAtualKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoProduto;
    private javax.swing.JPanel confirmar;
    private javax.swing.JTextField emEstoque;
    private javax.swing.JTextField estoqueAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox<String> produtos;
    private javax.swing.JSeparator separadorMovimentacao;
    private javax.swing.JSeparator separadorProduto;
    private javax.swing.JTextField valorMovimentacao;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
