/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jheni
 */
public class CadastroUsuario extends javax.swing.JPanel {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
        imagemCampoInválido.setVisible(false);
        UIManager.put("ToolTip.background", Color.RED);
    }
    private void verificaCamposValidos(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        separadorNome = new javax.swing.JSeparator();
        separadorCpf = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        separadorTelefone = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        separadorEmail = new javax.swing.JSeparator();
        nomeInvalido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        imagemCampoInválido = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        botaoConfirmar = new javax.swing.JPanel();
        labelConfirmar = new javax.swing.JLabel();
        separadorSenha = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(51, 51, 51));
        nome.setBorder(null);
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeKeyTyped(evt);
            }
        });
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 20));

        separadorNome.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 260, 10));

        separadorCpf.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, 10));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Senha:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Função:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        separadorTelefone.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 260, 10));

        email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 51));
        email.setBorder(null);
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 260, 20));

        cpf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("CPF:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        telefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        telefone.setForeground(new java.awt.Color(51, 51, 51));
        telefone.setBorder(null);
        add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 260, 20));

        separadorEmail.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 260, 10));

        nomeInvalido.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        add(nomeInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 410, 10));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nome:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 21, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Telefone:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        senha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        senha.setForeground(new java.awt.Color(51, 51, 51));
        senha.setBorder(null);
        add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 20));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButton1.setText("Administrador");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        imagemCampoInválido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imagemCampoInválido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Warning -WF.png"))); // NOI18N
        imagemCampoInválido.setToolTipText("Nome não pode conter números ou sinais de pontuação");
        add(imagemCampoInválido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButton2.setText("Colaborador");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("E-mail:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseExited(evt);
            }
        });
        botaoConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar.setText("Confirmar");
        labelConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelConfirmarMousePressed(evt);
            }
        });
        botaoConfirmar.add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 80, 30));

        separadorSenha.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        //        String conteudo = jTextField1.getText();
        //        String conteudoAvaliado = conteudo.replaceAll("[^ A-z]", "");
        //        System.out.println(conteudoAvaliado);
        //        //POSSO USAR O MATCH AQUI
        //        if (conteudo.equals(conteudoAvaliado) == false){
            //            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
            //            nomeInvalido.setForeground(Color.red);
            //            imagemCampoInválido.setVisible(true);
            //        } else {
            //            nomeInvalido.setText("");
            //            imagemCampoInválido.setVisible(false);
            //        }
        if (nome.getText().matches("[ a-zA-ZéúíóáÉÚÍÓÁèùìòàçÇÈÙÌÒÀõãñÕÃÑêûîôâÊÛÎÔÂëÿüïöäËYÜÏÖÄ]") == true){
            nomeInvalido.setText("");
            imagemCampoInválido.setVisible(false);
        } else {
            if(nome.getText().length() < 3){
                imagemCampoInválido.setToolTipText("Quantidade de caracteres inválida");
            } else {
                imagemCampoInválido.setToolTipText("Nome não pode conter números ou sinais de pontuação");
            }
            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
            nomeInvalido.setForeground(Color.red);
            imagemCampoInválido.setVisible(true);
        }
    }//GEN-LAST:event_nomeFocusLost

    private void nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyTyped

    }//GEN-LAST:event_nomeKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void labelConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseClicked
        JOptionPane.showMessageDialog(this, "clicou");
    }//GEN-LAST:event_labelConfirmarMouseClicked

    private void labelConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_labelConfirmarMouseEntered

    private void labelConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMouseExited

    private void labelConfirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMousePressed
        botaoConfirmar.setBackground(Color.white);
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMousePressed

    private void botaoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseClicked

    }//GEN-LAST:event_botaoConfirmarMouseClicked

    private void botaoConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_botaoConfirmarMouseEntered

    private void botaoConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_botaoConfirmarMouseExited

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoConfirmar;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JLabel imagemCampoInválido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeInvalido;
    private javax.swing.JTextField senha;
    private javax.swing.JSeparator separadorCpf;
    private javax.swing.JSeparator separadorEmail;
    private javax.swing.JSeparator separadorNome;
    private javax.swing.JSeparator separadorSenha;
    private javax.swing.JSeparator separadorTelefone;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
