/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.FornecedorService;
import controler.ProdutoService;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Produto;

/**
 *
 * @author Jheni
 */
public class ConsultaProdutoAtivo extends javax.swing.JPanel {
    
    JPanel paineis;
    EditaProduto editaProduto;
    
    List<Produto> listaProdutos;
    DefaultComboBoxModel padraoProdutos;
    
    public ConsultaProdutoAtivo(JPanel paineis, EditaProduto editaProduto) {
        initComponents();
        this.paineis = paineis;
        this.editaProduto = editaProduto;
        
        codigoInvalido.setVisible(false);
        
        atualizarProdutos();
    }
    
    public void atualizarProdutos() {
        listaProdutos = ProdutoService.pesquisaProdutosAtivos();

        padraoProdutos = new DefaultComboBoxModel();
        for (Produto p : listaProdutos) {
            padraoProdutos.addElement(p.getDescricao());
        }
        produtos.setModel(padraoProdutos);
    }
    
    public void atualizarInformacoes() {
        if (produtos.getSelectedIndex() != -1) {
            Produto p = listaProdutos.get(produtos.getSelectedIndex());
            
            codigoInformacoes.setText(p.getCodigo() + "");
            descricao.setText(p.getDescricao());
            categoria.setText(p.getCategoria());
            precoCusto.setText("R$ " +p.getpCusto());
            precoVenda.setText("R$ " + p.getpVenda());
            estoqueMinimo.setText(p.getEstoqueMinimo() + "");
            fornecedor.setText(FornecedorService.consultaFornecedorCnpj(p.getCnpjFornec()).getRazaoSocial());
            quantidade.setText(p.getQuantidade() + "");
        }
    }

    public void limparInformacoes() {
        codigoInformacoes.setText("");
        descricao.setText("");
        categoria.setText("");
        precoCusto.setText("");
        precoVenda.setText("");
        estoqueMinimo.setText("");
        fornecedor.setText("");
        quantidade.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JLabel();
        separadorCodigo = new javax.swing.JSeparator();
        codigo = new javax.swing.JFormattedTextField();
        produtos = new javax.swing.JComboBox<>();
        informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codigoInformacoes = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        precoCusto = new javax.swing.JLabel();
        precoVenda = new javax.swing.JLabel();
        estoqueMinimo = new javax.swing.JLabel();
        fornecedor = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();
        editar = new javax.swing.JPanel();
        editarLabel = new javax.swing.JLabel();
        desativar = new javax.swing.JPanel();
        desativarLabel = new javax.swing.JLabel();
        codigoInvalido = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setText("Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        separadorCodigo.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 10));

        codigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        try {
            codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        codigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFocusLost(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoKeyReleased(evt);
            }
        });
        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, -1));

        produtos.setBackground(new java.awt.Color(242, 242, 242));
        produtos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        produtos.setBorder(null);
        produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosActionPerformed(evt);
            }
        });
        add(produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 70, 560, 30));

        informacoes.setBackground(new java.awt.Color(255, 255, 255));
        informacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Categoria:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Preço de Custo:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Preço de Venda:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Estoque Mínimo:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Fornecedor:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Estoque atual:");

        codigoInformacoes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        descricao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        categoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        precoCusto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        precoVenda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        estoqueMinimo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        fornecedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        quantidade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout informacoesLayout = new javax.swing.GroupLayout(informacoes);
        informacoes.setLayout(informacoesLayout);
        informacoesLayout.setHorizontalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(descricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(categoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precoCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estoqueMinimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        informacoesLayout.setVerticalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informacoesLayout.createSequentialGroup()
                                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(informacoesLayout.createSequentialGroup()
                                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(informacoesLayout.createSequentialGroup()
                                                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(codigoInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                            .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(precoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(precoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );

        add(informacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 128, 780, -1));

        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarLabel.setText("Editar");
        editarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarLabelMouseExited(evt);
            }
        });
        editar.add(editarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 30));

        desativar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desativar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desativarLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        desativarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desativarLabel.setText("Desativar");
        desativarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desativarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                desativarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                desativarLabelMouseExited(evt);
            }
        });
        desativar.add(desativarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(desativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 541, 80, 30));

        codigoInvalido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fechar-mouse.png"))); // NOI18N
        add(codigoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "gerenciarProdutos");
    }//GEN-LAST:event_voltarMouseClicked

    private void codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFocusLost
        String codigo2 = codigo.getText().replace(" ", "");
        boolean entrou = false;
        if (codigo2.length() > 1 && codigo2.equals("0") == false) {
            codigoInvalido.setVisible(false);
            for (Produto p : listaProdutos) {
                if (p.getCodigo() == Integer.parseInt(codigo2)) {
                    entrou = true;
                    produtos.setSelectedIndex(listaProdutos.indexOf(p));
                    //padraoUsuarios.setSelectedItem(listaUsuarios.indexOf(u));
                    break;
                }
            }
            if (entrou == false) {
                codigoInvalido.setVisible(true);
                codigoInvalido.setToolTipText("Código não cadastrado.");
            }
        } else {
            codigoInvalido.setVisible(true);
            codigoInvalido.setToolTipText("Código inválido.");
        }
    }//GEN-LAST:event_codigoFocusLost

    private void codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyReleased
        if (evt.getKeyCode() == '\n') {
            codigo.transferFocus();
        }
    }//GEN-LAST:event_codigoKeyReleased

    private void produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosActionPerformed
        //atualizarUsuarios();
        atualizarInformacoes();
    }//GEN-LAST:event_produtosActionPerformed

    private void editarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarLabelMouseClicked
        if (produtos.getSelectedIndex() != -1) {
            CardLayout cartoes = (CardLayout) paineis.getLayout();
            editaProduto.resetaCamposInvalidos();
            editaProduto.inserirInformacoesProduto(listaProdutos.get(produtos.getSelectedIndex()));
            cartoes.show(paineis, "editaProduto");
        }
    }//GEN-LAST:event_editarLabelMouseClicked

    private void editarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarLabelMouseEntered
        editarLabel.setForeground(Color.white);
    }//GEN-LAST:event_editarLabelMouseEntered

    private void editarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarLabelMouseExited
        editarLabel.setForeground(Color.black);
    }//GEN-LAST:event_editarLabelMouseExited

    private void desativarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarLabelMouseClicked
        if (produtos.getSelectedIndex() != -1) {

            Produto p = listaProdutos.get(produtos.getSelectedIndex());
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja desativar o " + p.getDescricao() + "?");
            if (resposta == JOptionPane.OK_OPTION) {
                p.setAtivo(false);
                ProdutoService.alterarStatusProduto(p);

                limparInformacoes();
                atualizarProdutos();
                atualizarInformacoes();

                JOptionPane.showMessageDialog(this, p.getDescricao() + " foi desativado.");
            }
        }
    }//GEN-LAST:event_desativarLabelMouseClicked

    private void desativarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarLabelMouseEntered
        desativarLabel.setForeground(Color.white);
    }//GEN-LAST:event_desativarLabelMouseEntered

    private void desativarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarLabelMouseExited
        desativarLabel.setForeground(Color.black);
    }//GEN-LAST:event_desativarLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoria;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JLabel codigoInformacoes;
    private javax.swing.JLabel codigoInvalido;
    private javax.swing.JPanel desativar;
    private javax.swing.JLabel desativarLabel;
    private javax.swing.JLabel descricao;
    private javax.swing.JPanel editar;
    private javax.swing.JLabel editarLabel;
    private javax.swing.JLabel estoqueMinimo;
    private javax.swing.JLabel fornecedor;
    private javax.swing.JPanel informacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel precoCusto;
    private javax.swing.JLabel precoVenda;
    private javax.swing.JComboBox<String> produtos;
    private javax.swing.JLabel quantidade;
    private javax.swing.JSeparator separadorCodigo;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
