/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class ConsultaUsuario extends javax.swing.JPanel {
    JPanel paineis;
    /**
     * Creates new form ConsultaUsuario
     */
    public ConsultaUsuario(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        nome = new javax.swing.JTextField();
        separadorNome = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        botaoConfirmar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelConfirmar = new javax.swing.JLabel();
        desativar = new javax.swing.JPanel();
        labelConfirmar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aaaa", "aab", "baa", "caa", "abb" }));
        jComboBox1.setBorder(null);
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 70, 560, 30));

        nome.setBackground(new java.awt.Color(242, 242, 242));
        nome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(51, 51, 51));
        nome.setBorder(null);
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeKeyTyped(evt);
            }
        });
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 70, 130, 30));

        separadorNome.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 100, 130, 10));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseExited(evt);
            }
        });
        botaoConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 128, -1, -1));

        jLabel1.setText("Voltar");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        labelConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar.setText("Editar");
        labelConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelConfirmarMousePressed(evt);
            }
        });
        add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 541, 80, 30));

        desativar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desativar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desativarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                desativarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                desativarMouseExited(evt);
            }
        });
        desativar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConfirmar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelConfirmar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar1.setText("Desativar");
        labelConfirmar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConfirmar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConfirmar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConfirmar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelConfirmar1MousePressed(evt);
            }
        });
        desativar.add(labelConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(desativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 541, 80, 30));

        jLabel2.setText(" CPF:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        //        String conteudo = jTextField1.getText();
        //        String conteudoAvaliado = conteudo.replaceAll("[^ A-z]", "");
        //        System.out.println(conteudoAvaliado);
        //        //POSSO USAR O MATCH AQUI
        //        if (conteudo.equals(conteudoAvaliado) == false){
            //            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
            //            nomeInvalido.setForeground(Color.red);
            //            imagemCampoInválido.setVisible(true);
            //        } else {
            //            nomeInvalido.setText("");
            //            imagemCampoInválido.setVisible(false);
            //        }
    }//GEN-LAST:event_nomeFocusLost

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyTyped

    }//GEN-LAST:event_nomeKeyTyped

    private void labelConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseClicked
        JOptionPane.showMessageDialog(this, "clicou");
    }//GEN-LAST:event_labelConfirmarMouseClicked

    private void labelConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_labelConfirmarMouseEntered

    private void labelConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMouseExited

    private void labelConfirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMousePressed
        botaoConfirmar.setBackground(Color.white);
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMousePressed

    private void botaoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseClicked

    }//GEN-LAST:event_botaoConfirmarMouseClicked

    private void botaoConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_botaoConfirmarMouseEntered

    private void botaoConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_botaoConfirmarMouseExited

    private void desativarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarMouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_desativarMouseExited

    private void desativarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_desativarMouseEntered

    private void desativarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desativarMouseClicked

    }//GEN-LAST:event_desativarMouseClicked

    private void labelConfirmar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmar1MousePressed
        botaoConfirmar.setBackground(Color.white);
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmar1MousePressed

    private void labelConfirmar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmar1MouseExited
        botaoConfirmar.setBackground(new Color(240,240,240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmar1MouseExited

    private void labelConfirmar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmar1MouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_labelConfirmar1MouseEntered

    private void labelConfirmar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmar1MouseClicked
        JOptionPane.showMessageDialog(this, "clicou");
    }//GEN-LAST:event_labelConfirmar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoConfirmar;
    private javax.swing.JPanel desativar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JLabel labelConfirmar1;
    private javax.swing.JTextField nome;
    private javax.swing.JSeparator separadorNome;
    // End of variables declaration//GEN-END:variables
}
