/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.FornecedorService;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import model.Fornecedor;

/**
 *
 * @author Jheni
 */
public class ConsultaFornecedorAtivoColaborador extends javax.swing.JPanel {
    
    JPanel paineis;
    
    List<Fornecedor> listaFornecedores = new ArrayList<>();
    DefaultComboBoxModel padraoFornecedores;
    
    
    public ConsultaFornecedorAtivoColaborador(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
        
        cnpjInvalido.setVisible(false);
        
        atualizarFornecedores();
    }
    
    public void atualizarFornecedores() {
        listaFornecedores = FornecedorService.recuperaTodosFornecedoresAtivos();

        padraoFornecedores = new DefaultComboBoxModel();
        for (Fornecedor f : listaFornecedores) {
            padraoFornecedores.addElement(f.getRazaoSocial());
        }
        fornecedores.setModel(padraoFornecedores);
    }

    public void atualizarInformacoes() {
        if (fornecedores.getSelectedIndex() != -1) {
            Fornecedor f = listaFornecedores.get(fornecedores.getSelectedIndex());
            razaoSocial.setText(f.getRazaoSocial());
            cnpjFornecedor.setText(f.getCnpj());
            inscricaoEstadual.setText(f.getInscricaoEstadual());
            telefone.setText(f.getTelefone());
            endereco.setText(f.getEndereco());
            email.setText(f.getEmail());
        }
    }

    private void limparInformacoes(){
        razaoSocial.setText("");
        cnpjFornecedor.setText("");
        inscricaoEstadual.setText("");
        telefone.setText("");
        endereco.setText("");
        email.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorCpf = new javax.swing.JSeparator();
        fornecedores = new javax.swing.JComboBox<>();
        cnpj = new javax.swing.JFormattedTextField();
        cnpjInvalido = new javax.swing.JLabel();
        informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        razaoSocial = new javax.swing.JLabel();
        cnpjFornecedor = new javax.swing.JLabel();
        inscricaoEstadual = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 248, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorCpf.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 10));

        fornecedores.setBackground(new java.awt.Color(244, 248, 250));
        fornecedores.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        fornecedores.setForeground(new java.awt.Color(0, 8, 10));
        fornecedores.setBorder(null);
        fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedoresActionPerformed(evt);
            }
        });
        add(fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 560, 30));

        cnpj.setBackground(new java.awt.Color(244, 248, 250));
        cnpj.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cnpj.setForeground(new java.awt.Color(0, 8, 10));
        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnpjFocusLost(evt);
            }
        });
        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });
        cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnpjKeyReleased(evt);
            }
        });
        add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 30));

        cnpjInvalido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Attention_32px.png"))); // NOI18N
        add(cnpjInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 30, 30));

        informacoes.setBackground(new java.awt.Color(255, 255, 255));
        informacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 8, 10));
        jLabel1.setText("Razão Social:");

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 8, 10));
        jLabel3.setText("CNPJ:");

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 8, 10));
        jLabel4.setText("Inscrição Estadual:");

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 8, 10));
        jLabel5.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 8, 10));
        jLabel6.setText("Endereço:");

        jLabel7.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 8, 10));
        jLabel7.setText("E-mail:");

        razaoSocial.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        razaoSocial.setForeground(new java.awt.Color(0, 8, 10));

        cnpjFornecedor.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cnpjFornecedor.setForeground(new java.awt.Color(0, 8, 10));

        inscricaoEstadual.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        inscricaoEstadual.setForeground(new java.awt.Color(0, 8, 10));

        telefone.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        telefone.setForeground(new java.awt.Color(0, 8, 10));

        endereco.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        endereco.setForeground(new java.awt.Color(0, 8, 10));

        email.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 8, 10));

        javax.swing.GroupLayout informacoesLayout = new javax.swing.GroupLayout(informacoes);
        informacoes.setLayout(informacoesLayout);
        informacoesLayout.setHorizontalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cnpjFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(inscricaoEstadual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(razaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        informacoesLayout.setVerticalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informacoesLayout.createSequentialGroup()
                                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(informacoesLayout.createSequentialGroup()
                                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(cnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(inscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
        );

        add(informacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 740, 350));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 8, 10));
        jLabel2.setText("CNPJ:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedoresActionPerformed
        atualizarInformacoes();
    }//GEN-LAST:event_fornecedoresActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    private void cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpjFocusLost
        String cnpj2 = cnpj.getText().replace(" ", "");
        boolean entrou = false;

        if (cnpj2.length() == 18) {
            cnpjInvalido.setVisible(false);
            for (Fornecedor f : listaFornecedores) {
                if (f.getCnpj().equals(cnpj2)) {
                    entrou = true;
                    
                    System.out.println(f.getRazaoSocial());
                    
                    fornecedores.setSelectedIndex(listaFornecedores.indexOf(f));
                    //padraoUsuarios.setSelectedItem(listaUsuarios.indexOf(u));
                    break;
                }
            }
            if (entrou == false) {
                cnpjInvalido.setVisible(true);
                cnpjInvalido.setToolTipText("Fornecedor não cadastrado.");
            }
        } else {
            cnpjInvalido.setVisible(true);
            cnpjInvalido.setToolTipText("CNPJ inválido.");
        }
    }//GEN-LAST:event_cnpjFocusLost

    private void cnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnpjKeyReleased
        if (evt.getKeyCode() == '\n') {
            cnpj.transferFocus();
        }
    }//GEN-LAST:event_cnpjKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JLabel cnpjFornecedor;
    private javax.swing.JLabel cnpjInvalido;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JComboBox<String> fornecedores;
    private javax.swing.JPanel informacoes;
    private javax.swing.JLabel inscricaoEstadual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel razaoSocial;
    private javax.swing.JSeparator separadorCpf;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
