/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jheni
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Frame() {
        initComponents();
        this.setLayout(new BorderLayout());
//        this.getContentPane().add(painelPrincipal, BorderLayout.CENTER);
//        this.painelPrincipal.setViewportView(new TelaAdministrador());
        ((CardLayout)painelPrincipal.getLayout()).addLayoutComponent(painelPrincipal, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        painelUsuarios = new javax.swing.JPanel();
        cadastrarUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        painelCadastroUsuario = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        separadorNome = new javax.swing.JSeparator();
        separadorCpf = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        separadorTelefone = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        cpf = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        separadorEmail = new javax.swing.JSeparator();
        nomeInvalido = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        imagemCampoInválido = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        botaoConfirmar = new javax.swing.JPanel();
        labelConfirmar = new javax.swing.JLabel();
        separadorSenha = new javax.swing.JSeparator();
        voltarParaUsuario = new javax.swing.JLabel();
        painelRelatorios = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(231, 243, 239));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 243, 239));
        jLabel1.setText("Administrador");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(231, 243, 239));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 243, 239));
        jLabel2.setText("~nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(231, 243, 239));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 243, 239));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Movimentações");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 34));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(231, 243, 239));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(231, 243, 239));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Opções");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 220, 70));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(231, 243, 239));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(231, 243, 239));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Usuários");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 70));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(231, 243, 239));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 243, 239));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Relatórios");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 70));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(231, 243, 239));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 243, 239));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Produtos");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 70));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(231, 243, 239));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 243, 239));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Logoff");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 220, 70));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(231, 243, 239));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 243, 239));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fornecedores");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 34));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        painelPrincipal.setBackground(new java.awt.Color(102, 0, 102));
        painelPrincipal.setLayout(new java.awt.CardLayout());

        cadastrarUsuario.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        cadastrarUsuario.setText("Cadastrar Usuário");
        cadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarUsuarioMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jButton1.setText("Consultar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelUsuariosLayout = new javax.swing.GroupLayout(painelUsuarios);
        painelUsuarios.setLayout(painelUsuariosLayout);
        painelUsuariosLayout.setHorizontalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUsuariosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(cadastrarUsuario))
                .addContainerGap(483, Short.MAX_VALUE))
        );
        painelUsuariosLayout.setVerticalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUsuariosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cadastrarUsuario)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelUsuarios, "painelUsuarios");

        painelCadastroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(51, 51, 51));
        nome.setBorder(null);
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeKeyTyped(evt);
            }
        });
        painelCadastroUsuario.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 260, 20));

        separadorNome.setForeground(new java.awt.Color(51, 51, 51));
        painelCadastroUsuario.add(separadorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 260, 10));

        separadorCpf.setForeground(new java.awt.Color(51, 51, 51));
        painelCadastroUsuario.add(separadorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Senha:");
        painelCadastroUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Função:");
        painelCadastroUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        separadorTelefone.setForeground(new java.awt.Color(51, 51, 51));
        painelCadastroUsuario.add(separadorTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 260, 10));

        email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 51));
        email.setBorder(null);
        painelCadastroUsuario.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 260, 20));

        cpf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        painelCadastroUsuario.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("CPF:");
        painelCadastroUsuario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        telefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        telefone.setForeground(new java.awt.Color(51, 51, 51));
        telefone.setBorder(null);
        painelCadastroUsuario.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 260, 20));

        separadorEmail.setForeground(new java.awt.Color(51, 51, 51));
        painelCadastroUsuario.add(separadorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 260, 10));

        nomeInvalido.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        painelCadastroUsuario.add(nomeInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 410, 10));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nome:");
        painelCadastroUsuario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Telefone:");
        painelCadastroUsuario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        senha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        senha.setForeground(new java.awt.Color(51, 51, 51));
        senha.setBorder(null);
        painelCadastroUsuario.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 260, 20));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButton1.setText("Administrador");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        painelCadastroUsuario.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        imagemCampoInválido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        imagemCampoInválido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Warning -WF.png"))); // NOI18N
        imagemCampoInválido.setToolTipText("Nome não pode conter números ou sinais de pontuação");
        painelCadastroUsuario.add(imagemCampoInválido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButton2.setText("Colaborador");
        painelCadastroUsuario.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("E-mail:");
        painelCadastroUsuario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseExited(evt);
            }
        });
        botaoConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar.setText("Confirmar");
        labelConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConfirmarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelConfirmarMousePressed(evt);
            }
        });
        botaoConfirmar.add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        painelCadastroUsuario.add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 80, 30));

        separadorSenha.setForeground(new java.awt.Color(51, 51, 51));
        painelCadastroUsuario.add(separadorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 260, 10));

        voltarParaUsuario.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        voltarParaUsuario.setText("Voltar");
        voltarParaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarParaUsuarioMouseClicked(evt);
            }
        });
        painelCadastroUsuario.add(voltarParaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        painelPrincipal.add(painelCadastroUsuario, "painelCadastroUsuario");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel10.setText("RELATÓRIOS");

        javax.swing.GroupLayout painelRelatoriosLayout = new javax.swing.GroupLayout(painelRelatorios);
        painelRelatorios.setLayout(painelRelatoriosLayout);
        painelRelatoriosLayout.setHorizontalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatoriosLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel10)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        painelRelatoriosLayout.setVerticalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRelatoriosLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel10)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelRelatorios, "painelRelatorios");

        getContentPane().add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 860, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        //        String conteudo = jTextField1.getText();
        //        String conteudoAvaliado = conteudo.replaceAll("[^ A-z]", "");
        //        System.out.println(conteudoAvaliado);
        //        //POSSO USAR O MATCH AQUI
        //        if (conteudo.equals(conteudoAvaliado) == false){
        //            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
        //            nomeInvalido.setForeground(Color.red);
        //            imagemCampoInválido.setVisible(true);
        //        } else {
        //            nomeInvalido.setText("");
        //            imagemCampoInválido.setVisible(false);
        //        }
        if (nome.getText().matches("[ a-zA-ZéúíóáÉÚÍÓÁèùìòàçÇÈÙÌÒÀõãñÕÃÑêûîôâÊÛÎÔÂëÿüïöäËYÜÏÖÄ]") == true) {
            nomeInvalido.setText("");
            imagemCampoInválido.setVisible(false);
        } else {
            if (nome.getText().length() < 3) {
                imagemCampoInválido.setToolTipText("Quantidade de caracteres inválida");
            } else {
                imagemCampoInválido.setToolTipText("Nome não pode conter números ou sinais de pontuação");
            }
            nomeInvalido.setText("Nome não pode conter números ou sinais de pontuação");
            nomeInvalido.setForeground(Color.red);
            imagemCampoInválido.setVisible(true);
        }
    }//GEN-LAST:event_nomeFocusLost

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyTyped

    }//GEN-LAST:event_nomeKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void labelConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseClicked
        JOptionPane.showMessageDialog(this, "clicou");
    }//GEN-LAST:event_labelConfirmarMouseClicked

    private void labelConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_labelConfirmarMouseEntered

    private void labelConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240, 240, 240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMouseExited

    private void labelConfirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConfirmarMousePressed
        botaoConfirmar.setBackground(Color.white);
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_labelConfirmarMousePressed

    private void botaoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseClicked

    }//GEN-LAST:event_botaoConfirmarMouseClicked

    private void botaoConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseEntered
        botaoConfirmar.setBackground(Color.gray);
        labelConfirmar.setForeground(Color.white);
    }//GEN-LAST:event_botaoConfirmarMouseEntered

    private void botaoConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseExited
        botaoConfirmar.setBackground(new Color(240, 240, 240));
        labelConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_botaoConfirmarMouseExited

    private void cadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarUsuarioMouseClicked
        CardLayout cartoes = (CardLayout) painelPrincipal.getLayout();
        cartoes.show(painelPrincipal, "painelCadastroUsuario");

    }//GEN-LAST:event_cadastrarUsuarioMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        CardLayout cartoes = (CardLayout) painelPrincipal.getLayout();
        cartoes.show(painelPrincipal, "painelRelatorios");
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        CardLayout cartoes = (CardLayout) painelPrincipal.getLayout();
        cartoes.show(painelPrincipal, "painelUsuarios");
    }//GEN-LAST:event_jPanel11MouseClicked

    private void voltarParaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarParaUsuarioMouseClicked
        CardLayout cartoes = (CardLayout) painelPrincipal.getLayout();
        cartoes.show(painelPrincipal, "painelUsuarios");

    }//GEN-LAST:event_voltarParaUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
   //         UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");            
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoConfirmar;
    private javax.swing.JLabel cadastrarUsuario;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JLabel imagemCampoInválido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeInvalido;
    private javax.swing.JPanel painelCadastroUsuario;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelRelatorios;
    private javax.swing.JPanel painelUsuarios;
    private javax.swing.JTextField senha;
    private javax.swing.JSeparator separadorCpf;
    private javax.swing.JSeparator separadorEmail;
    private javax.swing.JSeparator separadorNome;
    private javax.swing.JSeparator separadorSenha;
    private javax.swing.JSeparator separadorTelefone;
    private javax.swing.JTextField telefone;
    private javax.swing.JLabel voltarParaUsuario;
    // End of variables declaration//GEN-END:variables

}
