/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class GerenciarUsuarios extends javax.swing.JPanel {
    
    JPanel paineis;
    ConsultaUsuarioAtivo consultaUsuarioAtivo;
    ConsultaUsuarioInativo consultaUsuarioInativo;


    public GerenciarUsuarios(JPanel paineis, ConsultaUsuarioAtivo consultaUsuarioAtivo, ConsultaUsuarioInativo consultaUsuarioInativo) {
        initComponents();
        this.paineis = paineis;
        this.consultaUsuarioAtivo = consultaUsuarioAtivo;
        this.consultaUsuarioInativo = consultaUsuarioInativo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar = new javax.swing.JPanel();
        cadastrarUsuario = new javax.swing.JLabel();
        consultaUsuarioInativoB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultaUsuarioAtivoB = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrarUsuario.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cadastrarUsuario.setText("Cadastrar Usuário");
        cadastrar.add(cadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, 190));

        consultaUsuarioInativoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaUsuarioInativoBMouseClicked(evt);
            }
        });
        consultaUsuarioInativoB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consultar Usuário Inativo");
        consultaUsuarioInativoB.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        add(consultaUsuarioInativoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 200, 190));

        consultaUsuarioAtivoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaUsuarioAtivoBMouseClicked(evt);
            }
        });
        consultaUsuarioAtivoB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Consultar Usuário Ativo");
        consultaUsuarioAtivoB.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        add(consultaUsuarioAtivoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void consultaUsuarioAtivoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaUsuarioAtivoBMouseClicked
        consultaUsuarioAtivo.atualizarUsuarios();
        consultaUsuarioAtivo.atualizarInformacoes();
        consultaUsuarioAtivo.editaUsuario.retornar = EditaUsuario.CONSULTA_ATIVOS;
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaUsuarioAtivo");
    }//GEN-LAST:event_consultaUsuarioAtivoBMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "cadastroUsuario");
    }//GEN-LAST:event_cadastrarMouseClicked

    private void consultaUsuarioInativoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaUsuarioInativoBMouseClicked
        consultaUsuarioInativo.atualizarUsuarios();
        consultaUsuarioInativo.atualizarInformacoes();
        consultaUsuarioAtivo.editaUsuario.retornar = EditaUsuario.CONSULTA_INATIVOS;
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaUsuarioInativo");
    }//GEN-LAST:event_consultaUsuarioInativoBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastrar;
    private javax.swing.JLabel cadastrarUsuario;
    private javax.swing.JPanel consultaUsuarioAtivoB;
    private javax.swing.JPanel consultaUsuarioInativoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
