/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class GerenciarFornecedores extends javax.swing.JPanel {
    JPanel paineis;
    /**
     * Creates new form GerenciarFornecedores
     */
    public GerenciarFornecedores(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFornecedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultarFornecedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarFornecedorMouseClicked(evt);
            }
        });
        cadastrarFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Cadastrar Fornecedor");
        cadastrarFornecedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        add(cadastrarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 200));

        consultarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarFornecedorMouseClicked(evt);
            }
        });
        consultarFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Consultar Fornecedor");
        consultarFornecedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        add(consultarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 200, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFornecedorMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "cadastroFornecedor");
    }//GEN-LAST:event_cadastrarFornecedorMouseClicked

    private void consultarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarFornecedorMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaFornecedor");
    }//GEN-LAST:event_consultarFornecedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastrarFornecedor;
    private javax.swing.JPanel consultarFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
