/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class GerenciarProdutos extends javax.swing.JPanel {
    
    JPanel paineis;
    ConsultaProdutoAtivo consultaProdutoAtivo;
    ConsultaProdutoInativo consultaProdutoInativo;
    CadastroProduto cadastroProduto;
    ProdutosEstoqueMinimo produtosEstoqueMinimo;
    
    public GerenciarProdutos(JPanel paineis, ConsultaProdutoAtivo consultaProdutoAtivo, ConsultaProdutoInativo consultaProdutoInativo, CadastroProduto cadastroProduto, ProdutosEstoqueMinimo produtosEstoqueMinimo) {
        initComponents();
        this.paineis = paineis;
        this.consultaProdutoAtivo = consultaProdutoAtivo;
        this.consultaProdutoInativo = consultaProdutoInativo;
        this.cadastroProduto = cadastroProduto;
        this.produtosEstoqueMinimo = produtosEstoqueMinimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produtosEstoqueMinimoAtingido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        consultarProdutoAtivo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consultarProdutoInativo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cadastrarProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 248, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produtosEstoqueMinimoAtingido.setBackground(new java.awt.Color(244, 248, 250));
        produtosEstoqueMinimoAtingido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produtosEstoqueMinimoAtingido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosEstoqueMinimoAtingidoMouseClicked(evt);
            }
        });
        produtosEstoqueMinimoAtingido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 8, 10));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clear Shopping Cart_100px.png"))); // NOI18N
        jLabel3.setText("Estoque Mínimo");
        produtosEstoqueMinimoAtingido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        add(produtosEstoqueMinimoAtingido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 410, 90));

        consultarProdutoAtivo.setBackground(new java.awt.Color(244, 248, 250));
        consultarProdutoAtivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarProdutoAtivo.setPreferredSize(new java.awt.Dimension(100, 100));
        consultarProdutoAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarProdutoAtivoMouseClicked(evt);
            }
        });
        consultarProdutoAtivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 8, 10));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search Property_100px.png"))); // NOI18N
        jLabel4.setText("Consultar Produto Ativo");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarProdutoAtivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(consultarProdutoAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 490, 100));

        consultarProdutoInativo.setBackground(new java.awt.Color(244, 248, 250));
        consultarProdutoInativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarProdutoInativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarProdutoInativoMouseClicked(evt);
            }
        });
        consultarProdutoInativo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 8, 10));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search Property_100px.png"))); // NOI18N
        jLabel2.setText("Consultar Produto Inativo");
        consultarProdutoInativo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(consultarProdutoInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 520, 100));

        cadastrarProduto.setBackground(new java.awt.Color(244, 248, 250));
        cadastrarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarProdutoMouseClicked(evt);
            }
        });
        cadastrarProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 8, 10));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add Shopping Cart_100px.png"))); // NOI18N
        jLabel1.setText("Cadastrar Produto");
        cadastrarProduto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        add(cadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 450, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProdutoMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cadastroProduto.atualizarListaFornecedores();
        cartoes.show(paineis, "cadastroProduto");
    }//GEN-LAST:event_cadastrarProdutoMouseClicked

    private void consultarProdutoInativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarProdutoInativoMouseClicked
        consultaProdutoInativo.atualizarProdutos();
        consultaProdutoInativo.atualizarInformacoes();
        consultaProdutoInativo.editaProduto.retornar = EditaProduto.CONSULTA_INATIVOS;
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaProdutoInativo");
    }//GEN-LAST:event_consultarProdutoInativoMouseClicked

    private void produtosEstoqueMinimoAtingidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosEstoqueMinimoAtingidoMouseClicked
        produtosEstoqueMinimo.atualizaProdutos();
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "produtosEstoqueMinimo");
        //ATUALIZAR A LISTA DE PRODUTOS****************************************************
    }//GEN-LAST:event_produtosEstoqueMinimoAtingidoMouseClicked

    private void consultarProdutoAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarProdutoAtivoMouseClicked
        consultaProdutoAtivo.atualizarProdutos();
        consultaProdutoAtivo.atualizarInformacoes();
        consultaProdutoAtivo.editaProduto.retornar = EditaProduto.CONSULTA_ATIVOS;
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaProdutoAtivo");
    }//GEN-LAST:event_consultarProdutoAtivoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastrarProduto;
    private javax.swing.JPanel consultarProdutoAtivo;
    private javax.swing.JPanel consultarProdutoInativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel produtosEstoqueMinimoAtingido;
    // End of variables declaration//GEN-END:variables
}
