/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class GerenciarUsuarios extends javax.swing.JPanel {
    JPanel paineis;
    /**
     * Creates new form GerenciarUsuarios
     */
    public GerenciarUsuarios(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar = new javax.swing.JPanel();
        cadastrarUsuario = new javax.swing.JLabel();
        consultaUsuarioInativo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultaUsuarioAtivo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrarUsuario.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cadastrarUsuario.setText("Cadastrar Usuário");
        cadastrar.add(cadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, 190));

        consultaUsuarioInativo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consultar Usuário Inativo");
        consultaUsuarioInativo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        add(consultaUsuarioInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 200, 190));

        consultaUsuarioAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaUsuarioAtivoMouseClicked(evt);
            }
        });
        consultaUsuarioAtivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Consultar Usuário Ativo");
        consultaUsuarioAtivo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        add(consultaUsuarioAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void consultaUsuarioAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaUsuarioAtivoMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "consultaUsuaroAtivo");
//
//        for (Component p : paineis.getComponents()){
//            try{
//                paineis.remove((ConsultaUsuarioAtivo)p);
//                paineis.add(new ConsultaUsuarioAtivo(paineis), "consultaUsuarioAtivo");
//                cartoes.show(paineis, "consultaUsuaroAtivo");
//            }catch (Exception ex){
//                System.out.println("erooou");
//            }
//        }
    }//GEN-LAST:event_consultaUsuarioAtivoMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "cadastroUsuario");
    }//GEN-LAST:event_cadastrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastrar;
    private javax.swing.JLabel cadastrarUsuario;
    private javax.swing.JPanel consultaUsuarioAtivo;
    private javax.swing.JPanel consultaUsuarioInativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
