/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class Movimentacoes extends javax.swing.JPanel {

    JPanel paineis;
    Baixa baixa;
    Entrada entrada;
    Devolucao devolucao;
    
    public Movimentacoes(JPanel paineis, Baixa baixa, Entrada entrada, Devolucao devolucao) {
        initComponents();
        this.paineis = paineis;
        this.baixa = baixa;
        this.entrada = entrada;
        this.devolucao = devolucao;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entradaB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        baixaB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        devolucaoB = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaB.setBackground(new java.awt.Color(204, 204, 204));
        entradaB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entradaB.setPreferredSize(new java.awt.Dimension(230, 230));
        entradaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaBMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Entrada");

        javax.swing.GroupLayout entradaBLayout = new javax.swing.GroupLayout(entradaB);
        entradaB.setLayout(entradaBLayout);
        entradaBLayout.setHorizontalGroup(
            entradaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradaBLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        entradaBLayout.setVerticalGroup(
            entradaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradaBLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        add(entradaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, 230));

        baixaB.setBackground(new java.awt.Color(204, 204, 204));
        baixaB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baixaB.setPreferredSize(new java.awt.Dimension(230, 230));
        baixaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baixaBMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Baixa");

        javax.swing.GroupLayout baixaBLayout = new javax.swing.GroupLayout(baixaB);
        baixaB.setLayout(baixaBLayout);
        baixaBLayout.setHorizontalGroup(
            baixaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baixaBLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(81, 81, 81))
        );
        baixaBLayout.setVerticalGroup(
            baixaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baixaBLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        add(baixaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        devolucaoB.setBackground(new java.awt.Color(204, 204, 204));
        devolucaoB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolucaoB.setPreferredSize(new java.awt.Dimension(230, 230));
        devolucaoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolucaoBMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Devolução");

        javax.swing.GroupLayout devolucaoBLayout = new javax.swing.GroupLayout(devolucaoB);
        devolucaoB.setLayout(devolucaoBLayout);
        devolucaoBLayout.setHorizontalGroup(
            devolucaoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucaoBLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        devolucaoBLayout.setVerticalGroup(
            devolucaoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucaoBLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel5)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        add(devolucaoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void entradaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaBMouseClicked
        entrada.atualizarProdutos();
        entrada.atualizarInformacoes();
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        
        cartoes.show(paineis, "entrada");
    }//GEN-LAST:event_entradaBMouseClicked

    private void baixaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baixaBMouseClicked
        baixa.atualizarProdutos();
        baixa.atualizarInformacoes();
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        
        cartoes.show(paineis, "baixa");
    }//GEN-LAST:event_baixaBMouseClicked

    private void devolucaoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucaoBMouseClicked
        devolucao.atualizarProdutos();
        devolucao.atualizarInformacoes();
        
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        
        cartoes.show(paineis, "devolucao");
    }//GEN-LAST:event_devolucaoBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baixaB;
    private javax.swing.JPanel devolucaoB;
    private javax.swing.JPanel entradaB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
