/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jheni
 */
public class Movimentacoes extends javax.swing.JPanel {

    JPanel paineis;

    public Movimentacoes(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        baixa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        devolucao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entrada.setBackground(new java.awt.Color(204, 204, 204));
        entrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrada.setPreferredSize(new java.awt.Dimension(230, 230));
        entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Entrada");

        javax.swing.GroupLayout entradaLayout = new javax.swing.GroupLayout(entrada);
        entrada.setLayout(entradaLayout);
        entradaLayout.setHorizontalGroup(
            entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        entradaLayout.setVerticalGroup(
            entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, 230));

        baixa.setBackground(new java.awt.Color(204, 204, 204));
        baixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baixa.setPreferredSize(new java.awt.Dimension(230, 230));
        baixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baixaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Baixa");

        javax.swing.GroupLayout baixaLayout = new javax.swing.GroupLayout(baixa);
        baixa.setLayout(baixaLayout);
        baixaLayout.setHorizontalGroup(
            baixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baixaLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(81, 81, 81))
        );
        baixaLayout.setVerticalGroup(
            baixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baixaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        add(baixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        devolucao.setBackground(new java.awt.Color(204, 204, 204));
        devolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolucao.setPreferredSize(new java.awt.Dimension(230, 230));
        devolucao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolucaoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Devolução");

        javax.swing.GroupLayout devolucaoLayout = new javax.swing.GroupLayout(devolucao);
        devolucao.setLayout(devolucaoLayout);
        devolucaoLayout.setHorizontalGroup(
            devolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucaoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        devolucaoLayout.setVerticalGroup(
            devolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucaoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel5)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        add(devolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "entrada");
    }//GEN-LAST:event_entradaMouseClicked

    private void baixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baixaMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "baixa");
    }//GEN-LAST:event_baixaMouseClicked

    private void devolucaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucaoMouseClicked
        CardLayout cartoes = (CardLayout) paineis.getLayout();
        cartoes.show(paineis, "devolucao");
    }//GEN-LAST:event_devolucaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baixa;
    private javax.swing.JPanel devolucao;
    private javax.swing.JPanel entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
