/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.FornecedorService;
import controler.MovimentacaoService;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Fornecedor;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jheni
 */
public class Relatorios extends javax.swing.JPanel {
    JPanel paineis;
    private ButtonGroup grupoRadioButton;

    List<Fornecedor> listaFornecedores = new ArrayList<>();
    DefaultComboBoxModel padraoFornecedores;
    
    public Relatorios(JPanel paineis) {
        initComponents();
        this.paineis = paineis;
        
        cnpjInvalido.setVisible(false);
        
        grupoRadioButton = new ButtonGroup();
        grupoRadioButton.add(pesquisarData);
        grupoRadioButton.add(pesquisarFornecedor);
    }
    
    public void atualizarFornecedores() {
        listaFornecedores = FornecedorService.recuperaTodosFornecedoresAtivos();

        padraoFornecedores = new DefaultComboBoxModel();
        for (Fornecedor f : listaFornecedores) {
            padraoFornecedores.addElement(f.getRazaoSocial());
        }
        fornecedores.setModel(padraoFornecedores);
    }

    public void modificaDataMaxima(){
        data1.setMaxSelectableDate(new Date());
        data2.setMaxSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorCpf = new javax.swing.JSeparator();
        fornecedores = new javax.swing.JComboBox<>();
        cnpj = new javax.swing.JFormattedTextField();
        cnpjInvalido = new javax.swing.JLabel();
        pesquisarFornecedor = new javax.swing.JRadioButton();
        pesquisarData = new javax.swing.JRadioButton();
        botaoConfirmar = new javax.swing.JPanel();
        labelConfirmar = new javax.swing.JLabel();
        data1 = new com.toedter.calendar.JDateChooser();
        data2 = new com.toedter.calendar.JDateChooser();
        dataLabel = new javax.swing.JLabel();
        cnpjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 248, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorCpf.setForeground(new java.awt.Color(51, 51, 51));
        add(separadorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, 10));

        fornecedores.setBackground(new java.awt.Color(244, 248, 250));
        fornecedores.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        fornecedores.setForeground(new java.awt.Color(0, 8, 10));
        fornecedores.setBorder(null);
        fornecedores.setEnabled(false);
        fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedoresActionPerformed(evt);
            }
        });
        add(fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 500, 30));

        cnpj.setBackground(new java.awt.Color(244, 248, 250));
        cnpj.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cnpj.setForeground(new java.awt.Color(0, 8, 10));
        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.setEnabled(false);
        cnpj.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnpjFocusLost(evt);
            }
        });
        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });
        cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnpjKeyReleased(evt);
            }
        });
        add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, 30));

        cnpjInvalido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Attention_32px.png"))); // NOI18N
        add(cnpjInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 30, 30));

        pesquisarFornecedor.setBackground(new java.awt.Color(244, 248, 250));
        pesquisarFornecedor.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        pesquisarFornecedor.setForeground(new java.awt.Color(0, 8, 10));
        pesquisarFornecedor.setText("Pesquisar por Fornecedor");
        pesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarFornecedorActionPerformed(evt);
            }
        });
        add(pesquisarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        pesquisarData.setBackground(new java.awt.Color(244, 248, 250));
        pesquisarData.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        pesquisarData.setForeground(new java.awt.Color(0, 8, 10));
        pesquisarData.setText("Pesquisar por Data:");
        pesquisarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarDataActionPerformed(evt);
            }
        });
        add(pesquisarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        botaoConfirmar.setBackground(new java.awt.Color(181, 212, 222));
        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseExited(evt);
            }
        });
        botaoConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConfirmar.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        labelConfirmar.setForeground(new java.awt.Color(0, 8, 10));
        labelConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmar.setText("Pesquisar");
        botaoConfirmar.add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 80, 30));

        data1.setBackground(new java.awt.Color(244, 248, 250));
        data1.setDate(new Date());
        data1.setEnabled(false);
        data1.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        data1.setMinSelectableDate(new java.util.Date(-62135755105000L));
        add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));

        data2.setBackground(new java.awt.Color(244, 248, 250));
        data2.setDate(new Date());
        data2.setEnabled(false);
        data2.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        data2.setMinSelectableDate(new java.util.Date(-62135755105000L));
        add(data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 180, -1));

        dataLabel.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(0, 8, 10));
        dataLabel.setText("De                                                        até");
        dataLabel.setEnabled(false);
        add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 280, -1));

        cnpjLabel.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cnpjLabel.setForeground(new java.awt.Color(0, 8, 10));
        cnpjLabel.setText("CNPJ:");
        cnpjLabel.setEnabled(false);
        add(cnpjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedoresActionPerformed

    }//GEN-LAST:event_fornecedoresActionPerformed

    private void cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpjFocusLost
        String cnpj2 = cnpj.getText().replace(" ", "");
        boolean entrou = false;

        if (cnpj2.length() == 18) {
            cnpjInvalido.setVisible(false);
            for (Fornecedor f : listaFornecedores) {
                if (f.getCnpj().equals(cnpj2)) {
                    entrou = true;

                    System.out.println(f.getRazaoSocial());

                    fornecedores.setSelectedIndex(listaFornecedores.indexOf(f));
                    //padraoUsuarios.setSelectedItem(listaUsuarios.indexOf(u));
                    break;
                }
            }
            if (entrou == false) {
                cnpjInvalido.setVisible(true);
                cnpjInvalido.setToolTipText("Fornecedor não cadastrado.");
            }
        } else {
            cnpjInvalido.setVisible(true);
            cnpjInvalido.setToolTipText("CNPJ inválido.");
        }
    }//GEN-LAST:event_cnpjFocusLost

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    private void cnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnpjKeyReleased
        if (evt.getKeyCode() == '\n') {
            cnpj.transferFocus();
        }
    }//GEN-LAST:event_cnpjKeyReleased

    private void pesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarFornecedorActionPerformed
        cnpj.setEnabled(true);
        cnpjLabel.setEnabled(true);
        fornecedores.setEnabled(true);
        
        dataLabel.setEnabled(false);
        data1.setEnabled(false);
        data2.setEnabled(false);
    }//GEN-LAST:event_pesquisarFornecedorActionPerformed

    private void pesquisarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarDataActionPerformed
        modificaDataMaxima();

        dataLabel.setEnabled(true);
        data1.setEnabled(true);
        data2.setEnabled(true);
        
        cnpj.setEnabled(false);
        cnpjLabel.setEnabled(false);
        cnpjInvalido.setVisible(false);
        fornecedores.setEnabled(false);
    }//GEN-LAST:event_pesquisarDataActionPerformed

    private void botaoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseClicked
        if (grupoRadioButton.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Nenhuma opção selecionada.");
        } else {
            if (pesquisarData.isSelected()){
                try {
                    JRResultSetDataSource resultSet;
                    if (data1.getDate().getTime() < data2.getDate().getTime()){
                        resultSet = new JRResultSetDataSource(MovimentacaoService.buscarMovimentacaoData(data1.getDate(), data2.getDate()));
                    } else {
                        resultSet = new JRResultSetDataSource(MovimentacaoService.buscarMovimentacaoData(data2.getDate(), data1.getDate()));
                    }
                    JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/relatorioPorData.jasper", new HashMap<>(), resultSet);
                    JasperViewer jv = new JasperViewer(jpPrint, false);
                    jv.setVisible(true);
                    jv.toFront();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Problema ao gerar relatório.");
                    ex.printStackTrace();
                }
                System.out.println("Data1: " + data1.getDate());
                System.out.println("Data2: " + data2.getDate());
            } else {
                try{        
                    JRResultSetDataSource resultSet = new JRResultSetDataSource(MovimentacaoService.buscaMovimentacaoFornecedor(listaFornecedores.get(fornecedores.getSelectedIndex()).getCnpj()));

                        JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/relatorioPorFornecedor.jasper", new HashMap<>(), resultSet);
                        JasperViewer jv = new JasperViewer(jpPrint, false);
                        jv.setVisible(true);
                        jv.toFront();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Problema ao gerar relatório.");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_botaoConfirmarMouseClicked

    private void botaoConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseEntered
    }//GEN-LAST:event_botaoConfirmarMouseEntered

    private void botaoConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseExited
    }//GEN-LAST:event_botaoConfirmarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoConfirmar;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JLabel cnpjInvalido;
    private javax.swing.JLabel cnpjLabel;
    private com.toedter.calendar.JDateChooser data1;
    private com.toedter.calendar.JDateChooser data2;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JComboBox<String> fornecedores;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JRadioButton pesquisarData;
    private javax.swing.JRadioButton pesquisarFornecedor;
    private javax.swing.JSeparator separadorCpf;
    // End of variables declaration//GEN-END:variables
}
